### ISSUE TITLE
PoloniexApiError

### ISSUE THREAD

**Issue by brandaspect** [Mikadily/poloniexlendingbot#103]
Hi Mikadily, 

I get the following error after poloniex.py line 38 

raise PoloniexApiError (data ['error'])
PoloniexApiError:Nonce must be greater than 147143430496300 You provided 1471430977750

Do you have any ideas on how to resolve this?

many thanks

Brandaspect

**Comment by rnevet** [comment]
https://github.com/Mikadily/poloniexlendingbot/wiki/FAQ-(Trouble-shooting)
Q: API request fails with ERROR: 'provided'

A: Means there was an issue accessing the API, things to check:

Are your API keys correct? No quotation. Just plain keys.
Are you using IP filter on the key? Maybe your IP changed?
Are you reusing the API key in multiple applications? use a unique key for every application.

**Comment by brandaspect** [comment]
Thanks for such a quick response, I created a new Api key and that solved it Thanks again

**Comment by rnevet** [comment]
Are you re-using the keys?  The nonce  isn't voodoo, current code should be fine.

**Comment by misthema** [comment]
I'm not sure if you saw my message, but the nonce format is different now.
Unix-timestamp isn't valid anymore (at least not for me, with any of my key-pairs). For some time now, it has required a nonce that big. Maybe it's because I've sent that format to it, so I need to use bigger than that? (not really sure how it works!)

**Comment by rnevet** [comment]
No, as I said before, check that you aren't re-using the key for multiple clients.
