### ISSUE TITLE
Feature Request - Leave coins in 'My Balance' if min lend rate not reached

### ISSUE THREAD

**Issue by AlexMinty** [Mikadily/poloniexlendingbot#46]
Rather than have our coins siting in the lending ledger at the max rate, leave them in 'My Balance' section. This would deflate the ledger, and lower the server hit on poloniex adding and removing coins ever XX seconds. Deflating the lending ledger could entice margin traders to borrow at higher rates instead of waiting for everything to continue getting lower and lower.

At the moment I have coins being added and removed every 60 seconds at .19%

Instead the lendingbot could wait until a users minimum lending rate is reached and then the coins would be added to the lending ledger. A % threshold could be added to catch an uptrend.

10% threshold example at 0.1% min lend rate: 

when lending rate reaches 0.09% lending bot will start adding coins to be lent out at .1% and up.

**Comment by Mikadily** [comment]
I know the code is not optimal and it was done this way because it was easier to code. But it's robust. "lower the server hit" is not our objective, if it would be really a problem for Poloniex they would introduce a request limit.

Other than that I like the idea of hidden coins. Kind of like phantom orders in trading. We could mess with borrowers a bit :) I'll think about it.

**Comment by AlexMinty** [comment]
'Other than that I like the idea of hidden coins. Kind of like phantom orders in trading.'
This is where I got the idea from. Thanks for the consideration! :)

**Comment by rnevet** [comment]
The latest update I did https://github.com/Mikadily/poloniexlendingbot/pull/48 changes the situation a bit, now if the ledger is full the bot will make the offers an minLendingRate and not maxLendingRate. 

We can still think about the idea of "phantom orders" and not place minLendingRate orders when realistically they only bloat the ledger - but we need a better specification, it's not only an issue of percentage "10% threshold example at 0.1% min lend rate" but also quantity - since the 10% can be with very small amount of coins of can be a huge wall.

**Comment by AlexMinty** [comment]
Awesome on the quick turnaround, haven't had a chance to try it out yet as I'm traveling for the next few days. Will be interesting to see the effect on rates once the majority of users move to it.
