### ISSUE TITLE
[Suggestion] Make the minimum amount for lending configurable

### ISSUE THREAD

**Issue by m33Lucky** [Mikadily/poloniexlendingbot#47]
I left the bot running after two days it was split into such small amount that the interest earn was slow and little , but over all bot is great getting rates way above my mindailyrate.

**Comment by RDash21** [comment]
I vouch for dis!

**Comment by Mikadily** [comment]
As I said on gitter:
https://github.com/Mikadily/poloniexlendingbot/blob/master/lendingbot.py#L152
this is the lowest amount the bot will bother to loan - it's hard coded at 0.001. You can modify it to your taste. But said that, I believe it won't help with microloans, because the borrower chooses how much he wants to borrow. And he can do it as small as satoshi. That's where majority of microloans are coming from.

**Comment by rnevet** [comment]
Currently we are discussing line:
https://github.com/Mikadily/poloniexlendingbot/blob/master/lendingbot.py#L174
```
def createLoanOffer(cur,amt,rate):
	days = '2'
	#if (minDailyRate - 0.000001) < rate and Decimal(amt) > 0.001:
	if float(amt) > 0.001:
```

I suggest the value of 0.001 should be configurable as minLoanAmount, possibly also per coin.

**Comment by rnevet** [comment]
Implemented
https://github.com/Mikadily/poloniexlendingbot/pull/68

A new configuration option named minLoanSize, default value is 0.001
