### ISSUE TITLE
API request fails with ERROR: 'provided'

### ISSUE THREAD

**Issue by lbg** [Mikadily/poloniexlendingbot#77]
Hey guys,

I am using ubuntu 14.04. 
Anyone would know how to help me with this error? It just keeps repeating the same message over and over since some days already. Before that is was working nicely.

luli@luli:~/poloniexlendingbot$ python lendingbot.py
Obtaining settings from config file.
Welcome to Poloniex Lending Bot
2016-06-07 23:45:40 ERROR: 'provided'
Traceback (most recent call last):
  File "lendingbot.py", line 457, in <module>
    refreshTotalLended()
  File "lendingbot.py", line 230, in refreshTotalLended
    for item in cryptoLended["provided"]:
KeyError: 'provided'

Any ideas will be much appreciated!
Thanks

**Comment by lbg** [comment]
already tried to change OS to windows and also changing API keys.

nothing solved do far..

**Comment by Evanito** [comment]
Is the bot the only thing accessing those API keys?

**Comment by lbg** [comment]
Yes. Also made a new key just for this matter.

**Comment by rnevet** [comment]
Are you using IP filter on the key? Maybe your IP changed?

**Comment by Evanito** [comment]
I am thinking that the issue lies in an incorrect nonce used, causing Poloniex to reject the API request. Even though the key and secret may be correct, using an outdated nonce (defined for the bot in line 49 of poloniex.py) will result in this error. 

You can tinker with the multiplier (increasing 1000 to 10000) and see if that solves it.The nonce is per API key, so if you get it impossibly high you may want to create a new key.

**Comment by lbg** [comment]
Raanan,

You were right. it was the IP stuff. I think it changed.

It's working now. Thank you guys!

Cheers
